# Generated by Django 3.0.6 on 2020-06-09 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item_status',
            fields=[
                ('item_code', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('item_name', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[{'AVAILABLE', 'Item ready to be purchased'}, {'Item Sold', 'SOLD'}, {'RESTOCKING', 'Item restocking in few days'}], default='AVAILABLE', max_length=50)),
                ('item_quantity_available', models.IntegerField()),
                ('issues', models.CharField(default='No issues', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='staff_member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('member_username', models.CharField(max_length=20, unique=True)),
                ('member_password', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_phone', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='sales_record',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('item_quantity_sold', models.IntegerField()),
                ('date_sold', models.DateTimeField(auto_now_add=True)),
                ('item_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item_status')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.staff_member')),
            ],
        ),
        migrations.CreateModel(
            name='reorder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date_reorder', models.DateTimeField()),
                ('quantity_reorder', models.IntegerField()),
                ('date_of_receive', models.DateTimeField(blank=True, null=True)),
                ('quantity_receive', models.IntegerField(blank=True, null=True)),
                ('remarks', models.CharField(default='No issue', max_length=100)),
                ('item_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item_status')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.staff_member')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier')),
            ],
        ),
    ]
