# Generated by Django 3.0.6 on 2020-06-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_status',
            name='item_code',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
