# Generated by Django 3.0.6 on 2020-06-09 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200609_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reorder',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='sales_record',
            name='staff',
        ),
        migrations.DeleteModel(
            name='staff_member',
        ),
    ]
