# Generated by Django 3.0.6 on 2020-06-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20200613_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reorder',
            name='date_of_receive',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reorder',
            name='date_reorder',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales_record',
            name='date_sold',
            field=models.DateField(auto_now_add=True),
        ),
    ]
